### ISSUE TITLE
用6.1版本训练的模型上传不成功

### ISSUE THREAD

**Issue by kankanjiuzou123** [exhyy/gradio-yolov5-lprnet#1]

**Comment by exhyy** [comment]
我自己测试6.0和6.1都可以用，6.2不行。请确保输出的类别数只有车牌一个类。
我在README里添加了6.0的yolov5s和6.1的yolov5s、yolov5m的权重，你可以试试

**Comment by kankanjiuzou123** [comment]
好的，我试一下
